// Import createSlice from Redux Toolkit, which helps create a slice of the Redux store
import { createSlice } from "@reduxjs/toolkit";

// Define the initial state for the counter with a starting value of 0
const initialState = { value: 0 };

// Create a slice named "counter" with the initial state and three reducers: increment, decrement, and incrementByValue
export const counterSlice = createSlice({
  name: "counter", // Name of the slice
  initialState,    // Initial state of the slice
  reducers: {
    // Reducer function to increment the counter by 1
    increment(state) {
      state.value++; // Increase the value by 1
    },
    // Reducer function to decrement the counter by 1
    decrement(state) {
      state.value--; // Decrease the value by 1
    },
    // Reducer function to increment the counter by a specified value
    incrementByValue(state, action) {
      state.value += action.payload; // Increase the value by the amount specified in action payload
    }
  }
});

// Export the actions (increment, decrement, and incrementByValue) generated by createSlice for use in components
export const { increment, decrement, incrementByValue } = counterSlice.actions;

// Export the reducer to be added to the Redux store
export default counterSlice.reducer;
