// Import createSlice from Redux Toolkit, which helps create a slice of the Redux store
import { createSlice } from "@reduxjs/toolkit";

// Define the initial state for the counter with a starting value of 0
const initialState = { value: 0 };

// Create a slice named "counter" with the initial state and two reducers: increment and decrement
export const counterSlice = createSlice({
  name: "counter", // Name of the slice
  initialState,    // Initial state of the slice
  reducers: {
    // Reducer function to increment the counter
    increment(state) {
      state.value++; // Increase the value by 1
    },
    // Reducer function to decrement the counter
    decrement(state) {
      state.value--; // Decrease the value by 1
    }
  }
});

// Export the actions (increment and decrement) generated by createSlice for use in components
export const { increment, decrement } = counterSlice.actions;

// Export the reducer to be added to the Redux store
export default counterSlice.reducer;
